# Generated by Django 3.2.8 on 2024-04-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='role',
            field=models.CharField(default='stu', max_length=20),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='college',
            field=models.CharField(default='计算机学院', max_length=20),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='userid',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
